/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.beautysalonmanagementsystme;

import com.beautysalonmanagementsystme.DAO.ServiceCatagoryDAO;
import com.beautysalonmanagementsystme.common.ICommonGUI;
import com.beautysalonmanagementsystme.model.ServiceCategory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CatagoryService_Product extends javax.swing.JFrame implements ICommonGUI {
    

    /**
     * Creates new form AA
     */
    DefaultTableModel model;
    ServiceCatagoryDAO catdao;
    public CatagoryService_Product() {
        initComponents();
        
        catdao=new ServiceCatagoryDAO();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        home_b = new javax.swing.JButton();
        par_b = new javax.swing.JButton();
        app_b = new javax.swing.JButton();
        client_b = new javax.swing.JButton();
        emp_b = new javax.swing.JButton();
        ser_b = new javax.swing.JButton();
        pro_b = new javax.swing.JButton();
        sale_b = new javax.swing.JButton();
        log_b = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SerTable = new javax.swing.JTable();
        Refreshbutton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeletButton = new javax.swing.JButton();
        _serviceEdit = new javax.swing.JTextField();
        ServiceCatagorySearchButton = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ServiceCatagoryCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ServiceCatagorytype = new javax.swing.JTextField();
        serviceCatagoryAddButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 123, 137));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/rsz_womenlogo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EDEN'S BEAUTY CARE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(412, 412, 412))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(228, 123, 137));
        jPanel2.setPreferredSize(new java.awt.Dimension(196, 618));

        home_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        home_b.setForeground(new java.awt.Color(0, 0, 255));
        home_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/home.png"))); // NOI18N
        home_b.setText("Home");
        home_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        home_b.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        home_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_bActionPerformed(evt);
            }
        });

        par_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        par_b.setForeground(new java.awt.Color(0, 0, 255));
        par_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/notebook.png"))); // NOI18N
        par_b.setText("Catagory");
        par_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        app_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        app_b.setForeground(new java.awt.Color(0, 0, 255));
        app_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/comment-pen.png"))); // NOI18N
        app_b.setText("Appoiment");
        app_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        app_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                app_bActionPerformed(evt);
            }
        });

        client_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        client_b.setForeground(new java.awt.Color(0, 0, 255));
        client_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/user-add.png"))); // NOI18N
        client_b.setText("Client");
        client_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        client_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_bActionPerformed(evt);
            }
        });

        emp_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        emp_b.setForeground(new java.awt.Color(0, 0, 255));
        emp_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/gingerbread-man.png"))); // NOI18N
        emp_b.setText("Employee ");
        emp_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emp_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_bActionPerformed(evt);
            }
        });

        ser_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ser_b.setForeground(new java.awt.Color(0, 0, 255));
        ser_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/time-twenty-four.png"))); // NOI18N
        ser_b.setText("Services");
        ser_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ser_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ser_bActionPerformed(evt);
            }
        });

        pro_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        pro_b.setForeground(new java.awt.Color(0, 0, 255));
        pro_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/boxes.png"))); // NOI18N
        pro_b.setText("Products");
        pro_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pro_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pro_bActionPerformed(evt);
            }
        });

        sale_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        sale_b.setForeground(new java.awt.Color(0, 0, 255));
        sale_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/ticket.png"))); // NOI18N
        sale_b.setText("Point Of Sale");
        sale_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sale_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sale_bActionPerformed(evt);
            }
        });

        log_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        log_b.setForeground(new java.awt.Color(0, 0, 255));
        log_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/sign-out-alt.png"))); // NOI18N
        log_b.setText("LogOut");
        log_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        log_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(par_b, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(app_b, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(client_b, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(ser_b, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(pro_b, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(sale_b, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(log_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(emp_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(home_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(par_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ser_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pro_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(client_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emp_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(app_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sale_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(log_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Manage Service Catagory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(560, 567));

        SerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service Catagory Code", "Service Catagory Type"
            }
        ));
        jScrollPane2.setViewportView(SerTable);

        Refreshbutton.setText("Refresh");
        Refreshbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshbuttonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update Catagory");

        DeletButton.setText("Delete Catagory");
        DeletButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletButtonMouseClicked(evt);
            }
        });
        DeletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletButtonActionPerformed(evt);
            }
        });

        _serviceEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _serviceEditActionPerformed(evt);
            }
        });

        ServiceCatagorySearchButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ServiceCatagorySearchButton.setText("Search :");
        ServiceCatagorySearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ServiceCatagorySearchButtonMouseClicked(evt);
            }
        });

        jLabel6.setText("Service Catagory Code");

        jLabel7.setText("Service Catagory Type");

        serviceCatagoryAddButton.setText("Add Catagory");
        serviceCatagoryAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceCatagoryAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(serviceCatagoryAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ServiceCatagorySearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(_serviceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(Refreshbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(DeletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ServiceCatagorytype, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ServiceCatagoryCode, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ServiceCatagoryCode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ServiceCatagorytype, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_serviceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ServiceCatagorySearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serviceCatagoryAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Refreshbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Manage Product Catagory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(560, 567));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Catagory Code", "Product Catagory Type"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Search :");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel4.setText("Catagory Product Code");

        jTextField2.setText("jTextField2");

        jLabel8.setText("Product Catagory  Type");

        jTextField3.setText("jTextField2");

        jButton8.setText("Add Catagory");

        jButton9.setText("Refresh");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Update Catagory");

        jButton11.setText("Delete Catagory");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void home_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_bActionPerformed
        // TODO add your handling code here:
        
         Menue_Frame mf=new Menue_Frame();
        this.dispose();
        mf.setVisible(true);
    }//GEN-LAST:event_home_bActionPerformed

    private void client_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_bActionPerformed
        // TODO add your handling code here:
         Clients_Details cdf=new Clients_Details();
         this.dispose();
        cdf.setVisible(true);
    }//GEN-LAST:event_client_bActionPerformed

    private void emp_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_bActionPerformed
        // TODO add your handling code here:
        Employee_Details ef=new Employee_Details();
         this.dispose();
        ef.setVisible(true);
    }//GEN-LAST:event_emp_bActionPerformed

    private void ser_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ser_bActionPerformed
        // TODO add your handling code here:
        Service_details sd=new Service_details();
         this.dispose();
        sd.setVisible(true);
    }//GEN-LAST:event_ser_bActionPerformed

    private void pro_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pro_bActionPerformed
        // TODO add your handling code here:
        Product_details pd=new Product_details();
         this.dispose();
        pd.setVisible(true);
    }//GEN-LAST:event_pro_bActionPerformed

    private void sale_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sale_bActionPerformed
        // TODO add your handling code here:
        Point_Sale ps=new Point_Sale();
         this.dispose();
        ps.setVisible(true);
    }//GEN-LAST:event_sale_bActionPerformed

    private void log_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_bActionPerformed
        // TODO add your handling code here:
        Log lf=new Log();
        this.dispose();
        lf.setVisible(true);

        
    }//GEN-LAST:event_log_bActionPerformed

    private void app_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_app_bActionPerformed
        // TODO add your handling code here:
        Appoinment_booking ab=new Appoinment_booking();
        this.dispose();
        ab.setVisible(true);
    }//GEN-LAST:event_app_bActionPerformed

    private void DeletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletButtonActionPerformed

    private void RefreshbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshbuttonActionPerformed
        // TODO add your handling code here:
        tab();
         
    }//GEN-LAST:event_RefreshbuttonActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void ServiceCatagorySearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiceCatagorySearchButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceCatagorySearchButtonMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void serviceCatagoryAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceCatagoryAddButtonActionPerformed
        // TODO add your handling code here:
        add();
       
        
    }//GEN-LAST:event_serviceCatagoryAddButtonActionPerformed

    private void DeletButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletButtonMouseClicked
        // TODO add your handling code here:
        
        deletrow();
    }//GEN-LAST:event_DeletButtonMouseClicked

    private void _serviceEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__serviceEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__serviceEditActionPerformed
   
   
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatagoryService_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatagoryService_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatagoryService_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatagoryService_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatagoryService_Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeletButton;
    private javax.swing.JButton Refreshbutton;
    private javax.swing.JTable SerTable;
    private javax.swing.JTextField ServiceCatagoryCode;
    private javax.swing.JLabel ServiceCatagorySearchButton;
    private javax.swing.JTextField ServiceCatagorytype;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField _serviceEdit;
    private javax.swing.JButton app_b;
    private javax.swing.JButton client_b;
    private javax.swing.JButton emp_b;
    private javax.swing.JButton home_b;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton log_b;
    private javax.swing.JButton par_b;
    private javax.swing.JButton pro_b;
    private javax.swing.JButton sale_b;
    private javax.swing.JButton ser_b;
    private javax.swing.JButton serviceCatagoryAddButton;
    // End of variables declaration//GEN-END:variables
    
    //<<<add catagory>>>>>>>>
    
    @Override
    public void add() {
        String serviceCatagoryCode=ServiceCatagoryCode.getText();
        String serviceCatagoryType=ServiceCatagorytype.getText();
        
        
        ServiceCategory servicecat=new ServiceCategory();
        servicecat.setServiceCatagorytype(serviceCatagoryType);
        servicecat.setServiceCatagoryCode(serviceCatagoryCode);
        
        
        int status=catdao.add(servicecat);
        if (status>0) {
            JOptionPane.showMessageDialog(rootPane, "Service Catagory is saved");
            
        } else{
             JOptionPane.showMessageDialog(rootPane, "Service Catagory is not saved");
        
        }
        
        
        
        
        
      
    }
    
    //show table
     public void tab(){
        model=(DefaultTableModel)SerTable.getModel();//get model na dile table dakha jabena
        
       // DefaultTableModel model=new DefaultTableModel();
        
//        model.addColumn("Catagory Type");
//        model.addColumn("Catagory Code");
//        //model.addColumn("Gender");
       
        try {
            String sql="SELECT*FROM catagory";
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/beautycare", "root", "root");
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            while (rs.next()) {
                String name=rs.getString("catagory_type");
               String code= rs.getString("catagory_code");
               //String gender= rs.getString("");
                Object[]rowdata={name,code};
                
                model.addRow(rowdata);
            }
            
             SerTable.setModel(model);
        } catch (Exception e) {
            System.out.println(e);
            
        }
       

    
    }
     
     //delete
      public void deletrow(){
    
    int countRow=SerTable.getSelectedRow();
       // Object obj=_table.getValueAt(countRow, 1);
        if (countRow==0) {
            model.removeRow(countRow);
            
        }else{
           
                JOptionPane.showMessageDialog(rootPane, "Table is empty");
                
            
        
    }                                      
    }
}



