/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.beautysalonmanagementsystme;

import com.beautysalonmanagementsystme.DAO.ServiceDAO;
import com.beautysalonmanagementsystme.common.ICommonGUI;
import com.beautysalonmanagementsystme.model.CustomerDetails;
import com.beautysalonmanagementsystme.model.Service;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Service_details extends javax.swing.JFrame implements ICommonGUI {

    
      
     DefaultTableModel model;
     ServiceDAO servicedao;
    public Service_details() {
        initComponents();
        servicedao=new ServiceDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        home_b = new javax.swing.JButton();
        par_b = new javax.swing.JButton();
        app_b = new javax.swing.JButton();
        client_b = new javax.swing.JButton();
        emp_b = new javax.swing.JButton();
        ser_b = new javax.swing.JButton();
        pro_b = new javax.swing.JButton();
        sale_b = new javax.swing.JButton();
        log_b = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton30 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        viewInformation = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SerTable = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        _serviceCode = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        _serviceCatagory = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        _serviceBarcode = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        _serviceDuration = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        _servicePrice = new javax.swing.JPasswordField();
        _serviceName = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        _serviceProduct = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 123, 137));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/rsz_womenlogo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EDEN'S BEAUTY CARE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(386, 386, 386)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(228, 123, 137));
        jPanel2.setPreferredSize(new java.awt.Dimension(196, 618));

        home_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        home_b.setForeground(new java.awt.Color(0, 0, 255));
        home_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/home.png"))); // NOI18N
        home_b.setText("Home");
        home_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        home_b.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        home_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_bActionPerformed(evt);
            }
        });

        par_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        par_b.setForeground(new java.awt.Color(0, 0, 255));
        par_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/notebook.png"))); // NOI18N
        par_b.setText("Parlour Details");
        par_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        par_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                par_bActionPerformed(evt);
            }
        });

        app_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        app_b.setForeground(new java.awt.Color(0, 0, 255));
        app_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/comment-pen.png"))); // NOI18N
        app_b.setText("Appoiment");
        app_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        app_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                app_bActionPerformed(evt);
            }
        });

        client_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        client_b.setForeground(new java.awt.Color(0, 0, 255));
        client_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/user-add.png"))); // NOI18N
        client_b.setText("Client");
        client_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        client_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_bActionPerformed(evt);
            }
        });

        emp_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        emp_b.setForeground(new java.awt.Color(0, 0, 255));
        emp_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/gingerbread-man.png"))); // NOI18N
        emp_b.setText("Employee ");
        emp_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emp_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_bActionPerformed(evt);
            }
        });

        ser_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ser_b.setForeground(new java.awt.Color(0, 0, 255));
        ser_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/time-twenty-four.png"))); // NOI18N
        ser_b.setText("Services");
        ser_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ser_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ser_bActionPerformed(evt);
            }
        });

        pro_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        pro_b.setForeground(new java.awt.Color(0, 0, 255));
        pro_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/boxes.png"))); // NOI18N
        pro_b.setText("Products");
        pro_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pro_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pro_bActionPerformed(evt);
            }
        });

        sale_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        sale_b.setForeground(new java.awt.Color(0, 0, 255));
        sale_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/ticket.png"))); // NOI18N
        sale_b.setText("Point Of Sale");
        sale_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sale_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sale_bActionPerformed(evt);
            }
        });

        log_b.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        log_b.setForeground(new java.awt.Color(0, 0, 255));
        log_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IconAndPicture/sign-out-alt.png"))); // NOI18N
        log_b.setText("LogOut");
        log_b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        log_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(par_b, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(app_b, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(client_b, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(ser_b, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(pro_b, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(sale_b, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(log_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(emp_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(home_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(par_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(app_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(client_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emp_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ser_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pro_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sale_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(log_b, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jButton30.setText("Delete Severice Information");

        jButton29.setText("Edit Service Information");

        jButton28.setText("Add New Service");
        jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton28MouseClicked(evt);
            }
        });

        viewInformation.setText("View Service Information");
        viewInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewInformationMouseClicked(evt);
            }
        });
        viewInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton32.setText("Save Service Information");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton28, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton32, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                        .addComponent(viewInformation, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                    .addComponent(jButton30, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jButton29, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap())
        );

        SerTable.setBackground(new java.awt.Color(153, 153, 153));
        SerTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SerTable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        SerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Service's Name", "Duration"
            }
        ));
        SerTable.setGridColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(SerTable);

        jLabel22.setText("Service Code");

        jLabel23.setText("Catagory ");

        _serviceCatagory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel24.setText("Barcode");

        _serviceBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _serviceBarcodeActionPerformed(evt);
            }
        });

        jLabel26.setText("Duration");

        _serviceDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _serviceDurationActionPerformed(evt);
            }
        });

        jLabel27.setText(" Price");

        _servicePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _servicePriceActionPerformed(evt);
            }
        });

        _serviceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _serviceNameActionPerformed(evt);
            }
        });

        jLabel29.setText("Product Details");

        jLabel30.setText("Service Name");

        _serviceProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _serviceProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(_serviceCode, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(_serviceBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(188, 188, 188))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(_serviceDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_servicePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_serviceCatagory, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_serviceName, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(408, 408, 408)
                    .addComponent(_serviceProduct)
                    .addGap(20, 20, 20)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_serviceCode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_serviceName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_serviceCatagory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_serviceBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_serviceDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_servicePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                    .addContainerGap(295, Short.MAX_VALUE)
                    .addComponent(_serviceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(198, 198, 198)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void home_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_bActionPerformed
        // TODO add your handling code here:
        
        
        Menue_Frame mf=new Menue_Frame();
        this.dispose();
        mf.setVisible(true);
    }//GEN-LAST:event_home_bActionPerformed

    private void client_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_bActionPerformed
        // TODO add your handling code here:
         Clients_Details cdf=new Clients_Details();
         this.dispose();
        cdf.setVisible(true);
    }//GEN-LAST:event_client_bActionPerformed

    private void emp_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_bActionPerformed
        // TODO add your handling code here:
         Employee_Details ef=new Employee_Details();
         this.dispose();
        ef.setVisible(true);
    }//GEN-LAST:event_emp_bActionPerformed

    private void ser_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ser_bActionPerformed
        // TODO add your handling code here:
        Service_details sd=new Service_details();
         this.dispose();
        sd.setVisible(true);
    }//GEN-LAST:event_ser_bActionPerformed

    private void pro_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pro_bActionPerformed
        // TODO add your handling code here:
        Product_details pd=new Product_details();
         this.dispose();
        pd.setVisible(true);
    }//GEN-LAST:event_pro_bActionPerformed

    private void sale_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sale_bActionPerformed
        // TODO add your handling code here:
        Point_Sale ps=new Point_Sale();
         this.dispose();
        ps.setVisible(true);
    }//GEN-LAST:event_sale_bActionPerformed

    private void log_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_bActionPerformed
        // TODO add your handling code here:
        Log lf=new Log();
        this.dispose();
        lf.setVisible(true);

        
    }//GEN-LAST:event_log_bActionPerformed

    private void app_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_app_bActionPerformed
        // TODO add your handling code here:
         Appoinment_booking ab=new Appoinment_booking();
        this.dispose();
        ab.setVisible(true);
    }//GEN-LAST:event_app_bActionPerformed

    private void par_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_par_bActionPerformed
        // TODO add your handling code here:
        CatagoryService_Product bcd=new CatagoryService_Product();
        this.dispose();
        bcd.setVisible(true);
    }//GEN-LAST:event_par_bActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void _serviceBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__serviceBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__serviceBarcodeActionPerformed

    private void _servicePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__servicePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__servicePriceActionPerformed

    private void _serviceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__serviceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__serviceNameActionPerformed

    private void viewInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewInformationMouseClicked
        // TODO add your handling code here:
           serviceTable();

    }//GEN-LAST:event_viewInformationMouseClicked

    private void _serviceProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__serviceProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__serviceProductActionPerformed

    private void _serviceDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__serviceDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__serviceDurationActionPerformed

    private void jButton28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseClicked
        // TODO add your handling code here:
        add();
    }//GEN-LAST:event_jButton28MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Service_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Service_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Service_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Service_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Service_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SerTable;
    private javax.swing.JTextField _serviceBarcode;
    private javax.swing.JComboBox _serviceCatagory;
    private javax.swing.JTextField _serviceCode;
    private javax.swing.JTextField _serviceDuration;
    private javax.swing.JTextField _serviceName;
    private javax.swing.JPasswordField _servicePrice;
    private javax.swing.JTextField _serviceProduct;
    private javax.swing.JButton app_b;
    private javax.swing.JButton client_b;
    private javax.swing.JButton emp_b;
    private javax.swing.JButton home_b;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton32;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton log_b;
    private javax.swing.JButton par_b;
    private javax.swing.JButton pro_b;
    private javax.swing.JButton sale_b;
    private javax.swing.JButton ser_b;
    private javax.swing.JButton viewInformation;
    // End of variables declaration//GEN-END:variables

    @Override
    public void add() {
       String serviceCode=_serviceCode.getText();
       String serviceName=_serviceName.getText();
       String serviceCatagory=_serviceCatagory.getSelectedItem().toString();
       String serviceBarcode=_serviceBarcode.getText();
       String serviceProductDetail=_serviceProduct.getText();
       int serviceDuration=Integer.parseInt(_serviceDuration.getText());
       
       int servicePrice=Integer.parseInt(_servicePrice.getText());
       
      
       
       
       
        Service service=new Service();
        service.setServiceCode(serviceCode);
        service.setServiceName(serviceName);
        service.setServiceCatagory(serviceCatagory);
        service.setServiceBarcode(serviceBarcode);
        service.setServiceProductDetails(serviceProductDetail);
        service.setServiceDuration(serviceDuration);
        service.setServicePrice(servicePrice);
       
        
        
        
        int status=servicedao.add(service);
        if (status>0) {
            JOptionPane.showMessageDialog(rootPane, "Registration successful");
            
        } else{
             JOptionPane.showMessageDialog(rootPane, "Registration unsuccessful");
        
        }
        
    }
    public void serviceTable(){
        model=(DefaultTableModel) SerTable.getModel();//get model na dile table dakha jabena
         model.setRowCount(0);
        //DefaultTableModel model=new DefaultTableModel();
        
//        model.addColumn("Catagory Type");
//        model.addColumn("Catagory Code");
        //model.addColumn("Gender");
       
        try {
            String sql="SELECT*FROM service";
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/beautycare", "root", "root");
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            while (rs.next()) {
                String code=rs.getString("service_code");
               String name= rs.getString("service_name");
               String duration= rs.getString("service_duration");
               //String gender= rs.getString("");
                Object[]rowdata={code,name,duration};
                
                model.addRow(rowdata);
            }
            
             SerTable.setModel(model);
        } catch (Exception e) {
            System.out.println(e);
            
        }
       

    
    }
}
